import localFont from "next/font/local";
import type { Metadata } from "next";
import "./globals.css";

const geistFont = localFont({
  src: "./font/GeistVF.woff2",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={geistFont.className}>{children}</body>
    </html>
  );
}
